// <auto-generated />
using System;
using ASF.EntityFramework.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASF.EntityFramework.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("ASF.Infrastructure.Model.AccountModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar")
                        .HasMaxLength(225);

                    b.Property<int>("CreateId");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Email");

                    b.Property<DateTime>("Expired");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LoginIp")
                        .HasMaxLength(20);

                    b.Property<DateTime>("LoginTime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("RefreshToken");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasMaxLength(20000);

                    b.Property<int>("Status");

                    b.Property<string>("Telephone");

                    b.Property<string>("Token");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("ASF.Infrastructure.Model.LogInfoModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccountId");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<DateTime>("AddTime");

                    b.Property<string>("ApiAddress")
                        .HasMaxLength(500);

                    b.Property<string>("ApiRequest");

                    b.Property<string>("ApiResponse");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("PermissionId")
                        .HasMaxLength(150);

                    b.Property<string>("Remark")
                        .HasMaxLength(500);

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("LogInfos");
                });

            modelBuilder.Entity("ASF.Infrastructure.Model.PermissionModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100);

                    b.Property<string>("ApiTemplate")
                        .HasMaxLength(500);

                    b.Property<string>("Code")
                        .IsRequired();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Description")
                        .HasMaxLength(200);

                    b.Property<bool>("Enable");

                    b.Property<bool>("IsLogger");

                    b.Property<bool>("IsSystem");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ParentId")
                        .HasMaxLength(100);

                    b.Property<int>("Sort");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("ASF.Infrastructure.Model.RoleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CreateId");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Description")
                        .HasMaxLength(200);

                    b.Property<bool>("Enable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Permissions")
                        .HasMaxLength(20000);

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
